version: "3.8"
services:
  db:
    container_name: warehousedb
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=warehousedb
