INSERT INTO PRODUCT(TITLE, ARTICLE, DESCRIPTION, PRICE, IMAGE)
SELECT 'Медведь', 10001, 'Плюшевый медведь коричневого цвета', 13.99, '/bear10001'
WHERE NOT EXISTS(SELECT * FROM tariff WHERE ARTICLE = 10001);